version: '3'
services:
  mysql:
    image: mysql:5.7.36
    restart: always
    container_name: mysql
    command:
      --default_authentication_plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    ports:
      - "21406:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/var/lib/mysql:/var/lib/mysql
      - $PWD/mysqlBackup:/data/mysqlBackup
    environment:
      - MYSQL_ROOT_PASSWORD: your password
